// Generated by scripts/generate-protocol.mjs; do not edit.
#[derive(Debug, serde::Serialize)]
pub struct RuntimeStatus {
    schema_version: u32,
    product: &'static str,
    phase: &'static str,
    execution_enabled: bool,
}

pub fn scaffold_status() -> RuntimeStatus {
    RuntimeStatus {
        schema_version: 1,
        product: "runweft",
        phase: "scaffold",
        execution_enabled: false,
    }
}
