// Generated by scripts/generate-protocol.mjs; do not edit.
// Source: schemas/run-protocol.schema.json (JSON Schema Draft 2020-12).
export type Identifier = string;
export type Digest = string;
export type Unsigned64 = string;
export type PositiveUnsigned64 = string;
export type MicroUsd = string;
export type ObservedAt = string;
export type Extensions = { [key: string]: ExtensionValue };
export type ExtensionValue = null | boolean | string | ExtensionValue[] | { [key: string]: ExtensionValue };
export type Actor = {
  "kind": "user" | "coordinator" | "worker" | "reconciler";
  "id": Identifier;
};
export type LeaseBinding = {
  "profile_id": Identifier;
  "project_id": Identifier;
  "run_id": Identifier;
  "task_id": Identifier;
  "attempt_id": Identifier;
  "lease_id": Identifier;
  "profile_incarnation": Identifier;
  "coordinator_generation": PositiveUnsigned64;
  "epoch": PositiveUnsigned64;
};
export type ErrorCode = "unsupported_version" | "unknown_critical_variant" | "malformed_payload" | "unknown_field" | "stale_profile_incarnation" | "stale_coordinator_generation" | "stale_lease" | "invalid_state_transition" | "conflict" | "not_found" | "unauthorized" | "resource_exhausted" | "requires_confirmation" | "unknown_effect" | "internal";
export type ErrorBody = {
  "code": ErrorCode;
};
export type RunState = "admitted" | "running" | "awaiting_approval" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown_effect";
export type GraphRevisionState = "draft" | "validated" | "admitted" | "rejected" | "superseded";
export type TaskState = "queued" | "ready" | "running" | "verifying" | "awaiting_approval" | "paused" | "succeeded" | "failed" | "cancelled" | "unknown_effect" | "skipped";
export type AttemptState = "created" | "dispatched" | "running" | "awaiting_approval" | "paused" | "verifying" | "succeeded" | "failed" | "cancelled" | "unknown_effect" | "reconciled";
export type EffectState = "recorded" | "authorized" | "invoking" | "applied" | "failed" | "cancelled" | "unknown_effect" | "reconciled_applied" | "reconciled_not_applied";
export type RunSubmitPayload = {
  "run_id": Identifier;
  "graph_revision_id": Identifier;
  "graph_digest": Digest;
  "requested_budget_micro_usd": MicroUsd;
};
export type RunIdPayload = {
  "run_id": Identifier;
  "reason"?: "user_request" | "policy_change" | "operator_action";
};
export type EffectApprovalPayload = {
  "run_id": Identifier;
  "effect_intent_id": Identifier;
  "action_id": Identifier;
  "target_id": Identifier;
  "artifact_digest": Digest;
  "action_digest": Digest;
  "grant_revision_id": Identifier;
  "policy_revision_id": Identifier;
};
export type AttemptResultSubmittedPayload = {
  "run_id": Identifier;
  "task_id": Identifier;
  "attempt_id": Identifier;
  "lease": LeaseBinding;
  "artifact_digest": Digest;
};
export type EffectIntentRecordedPayload = {
  "run_id": Identifier;
  "task_id": Identifier;
  "attempt_id": Identifier;
  "lease": LeaseBinding;
  "effect_intent_id": Identifier;
  "action_id": Identifier;
  "target_id": Identifier;
  "artifact_digest": Digest;
  "action_digest": Digest;
  "grant_revision_id": Identifier;
  "policy_revision_id": Identifier;
  "effect_class": "read_only" | "remote_idempotent" | "externally_reconcilable" | "opaque_non_idempotent";
};
export type EffectReconciliationProposalPayload = {
  "run_id": Identifier;
  "effect_intent_id": Identifier;
  "evidence_source_id": Identifier;
  "evidence_digest": Digest;
  "claimed_outcome": "applied" | "not_applied" | "unresolved";
};
export type EffectReconciledPayload = {
  "run_id": Identifier;
  "effect_intent_id": Identifier;
  "from_state": "unknown_effect";
  "to_state": "reconciled_applied" | "reconciled_not_applied";
  "action_digest": Digest;
  "target_id": Identifier;
  "artifact_digest": Digest;
  "lease": LeaseBinding;
  "evidence_source_id": Identifier;
  "evidence_digest": Digest;
  "outcome": "applied" | "not_applied";
};
export type RunSubmitCommand = CommandBase & {
  "variant"?: "run.submit";
  "payload"?: RunSubmitPayload;
  [key: string]: unknown;
};
export type RunPauseCommand = CommandBase & {
  "variant"?: "run.pause";
  "payload"?: RunIdPayload;
  [key: string]: unknown;
};
export type RunResumeCommand = CommandBase & {
  "variant"?: "run.resume";
  "payload"?: RunIdPayload;
  [key: string]: unknown;
};
export type RunCancelCommand = CommandBase & {
  "variant"?: "run.cancel";
  "payload"?: RunIdPayload;
  [key: string]: unknown;
};
export type EffectApproveCommand = CommandBase & {
  "variant"?: "effect.approve";
  "payload"?: EffectApprovalPayload;
  [key: string]: unknown;
};
export type EffectReconcileCommand = CommandBase & {
  "variant"?: "effect.reconciliation.propose";
  "payload"?: EffectReconciliationProposalPayload;
  [key: string]: unknown;
};
export type AttemptResultSubmitCommand = CommandBase & {
  "variant"?: "attempt.result.submit";
  "payload"?: AttemptResultSubmittedPayload;
  [key: string]: unknown;
};
export type CommandMessage = RunSubmitCommand | RunPauseCommand | RunResumeCommand | RunCancelCommand | EffectApproveCommand | EffectReconcileCommand | AttemptResultSubmitCommand;
export type CommandBase = {
  "protocol_version": "1.0";
  "kind": "command";
  "variant": string;
  "command_id": Identifier;
  "profile_id": Identifier;
  "project_id": Identifier;
  "profile_incarnation": Identifier;
  "coordinator_generation": PositiveUnsigned64;
  "payload": { [key: string]: unknown };
  "extensions"?: Extensions;
};
export type RunAdmittedPayload = {
  "run_id": Identifier;
  "graph_revision_id": Identifier;
  "graph_digest": Digest;
};
export type RunStateChangedPayload = {
  "run_id": Identifier;
  "from_state": RunState;
  "to_state": RunState;
};
export type GraphRevisionStateChangedPayload = {
  "graph_revision_id": Identifier;
  "from_state": GraphRevisionState;
  "to_state": GraphRevisionState;
  "graph_digest": Digest;
};
export type TaskStateChangedPayload = {
  "task_id": Identifier;
  "from_state": TaskState;
  "to_state": TaskState;
  "attempt_id"?: Identifier;
  "verification_receipt_id"?: Identifier;
};
export type AcceptedAttemptResult = {
  "result_id": Identifier;
  "run_id": Identifier;
  "task_id": Identifier;
  "attempt_id": Identifier;
  "lease": LeaseBinding;
  "artifact_digest": Digest;
};
export type VerificationReceipt = {
  "receipt_id": Identifier;
  "run_id": Identifier;
  "task_id": Identifier;
  "attempt_id": Identifier;
  "artifact_digest": Digest;
  "verifier_id": Identifier;
  "evidence_digest": Digest;
  "observed_at": ObservedAt;
};
export type AttemptStateChangedPayload = {
  "task_id": Identifier;
  "attempt_id": Identifier;
  "from_state": AttemptState;
  "to_state": AttemptState;
  "lease_epoch"?: PositiveUnsigned64;
  "accepted_result"?: AcceptedAttemptResult;
  "verification_receipt"?: VerificationReceipt;
};
export type EffectStateChangedPayload = {
  "effect_intent_id": Identifier;
  "from_state": EffectState;
  "to_state": EffectState;
  "receipt"?: EffectReceipt;
  "not_applied_evidence"?: EvidenceReference;
};
export type EvidenceReference = {
  "source_id": Identifier;
  "digest": Digest;
};
export type EffectReceipt = {
  "receipt_id": Identifier;
  "effect_intent_id": Identifier;
  "action_digest": Digest;
  "target_id": Identifier;
  "artifact_digest": Digest;
  "lease": LeaseBinding;
  "evidence_source_id": Identifier;
  "evidence_digest": Digest;
  "observed_at": ObservedAt;
};
export type RunAdmittedEvent = EventBase & {
  "variant"?: "run.admitted";
  "payload"?: RunAdmittedPayload;
  [key: string]: unknown;
};
export type RunStateChangedEvent = EventBase & {
  "variant"?: "run.state.changed";
  "payload"?: RunStateChangedPayload;
  [key: string]: unknown;
};
export type GraphRevisionStateChangedEvent = EventBase & {
  "variant"?: "graph.revision.state.changed";
  "payload"?: GraphRevisionStateChangedPayload;
  [key: string]: unknown;
};
export type TaskStateChangedEvent = EventBase & {
  "variant"?: "task.state.changed";
  "payload"?: TaskStateChangedPayload;
  [key: string]: unknown;
};
export type AttemptStateChangedEvent = EventBase & {
  "variant"?: "attempt.state.changed";
  "payload"?: AttemptStateChangedPayload;
  [key: string]: unknown;
};
export type EffectIntentRecordedEvent = EventBase & {
  "variant"?: "effect.intent.recorded";
  "payload"?: EffectIntentRecordedPayload;
  [key: string]: unknown;
};
export type EffectReconciledEvent = EventBase & {
  "variant"?: "effect.reconciled";
  "payload"?: EffectReconciledPayload;
  [key: string]: unknown;
};
export type EffectStateChangedEvent = EventBase & {
  "variant"?: "effect.state.changed";
  "payload"?: EffectStateChangedPayload;
  [key: string]: unknown;
};
export type EventMessage = RunAdmittedEvent | RunStateChangedEvent | GraphRevisionStateChangedEvent | TaskStateChangedEvent | AttemptStateChangedEvent | EffectIntentRecordedEvent | EffectStateChangedEvent | EffectReconciledEvent;
export type EventBase = {
  "protocol_version": "1.0";
  "kind": "event";
  "variant": string;
  "event_id": Identifier;
  "profile_id": Identifier;
  "project_id": Identifier;
  "profile_incarnation": Identifier;
  "coordinator_generation": PositiveUnsigned64;
  "run_id": Identifier;
  "sequence": PositiveUnsigned64;
  "causation_id": Identifier;
  "actor": Actor;
  "graph_revision_id": Identifier;
  "policy_revision_id": Identifier;
  "observed_at": ObservedAt;
  "payload": { [key: string]: unknown };
  "extensions"?: Extensions;
};
export type AcceptedResponsePayload = {
  "command_id": Identifier;
  "event_sequence": PositiveUnsigned64;
};
export type RejectedResponsePayload = {
  "command_id": Identifier;
  "error": ErrorBody;
};
export type AcceptedResponse = ResponseBase & {
  "variant"?: "command.accepted";
  "payload"?: AcceptedResponsePayload;
  [key: string]: unknown;
};
export type RejectedResponse = ResponseBase & {
  "variant"?: "command.rejected";
  "payload"?: RejectedResponsePayload;
  [key: string]: unknown;
};
export type ResponseMessage = AcceptedResponse | RejectedResponse;
export type ResponseBase = {
  "protocol_version": "1.0";
  "kind": "response";
  "variant": string;
  "correlation_id": Identifier;
  "profile_id": Identifier;
  "project_id": Identifier;
  "profile_incarnation": Identifier;
  "coordinator_generation": PositiveUnsigned64;
  "payload": { [key: string]: unknown };
  "extensions"?: Extensions;
};
export type ProtocolErrorMessage = ErrorBase & {
  "variant"?: "protocol.error";
  "payload"?: ErrorBody;
  [key: string]: unknown;
};
export type ErrorMessage = ProtocolErrorMessage;
export type ErrorBase = {
  "protocol_version": "1.0";
  "kind": "error";
  "variant": string;
  "correlation_id": Identifier;
  "payload": { [key: string]: unknown };
};
export type ProtocolMessage = CommandMessage | EventMessage | ResponseMessage | ErrorMessage;
