// Generated by scripts/generate-status.mjs; do not edit.
export const SCAFFOLD_STATUS = Object.freeze({
  "schema_version": 1,
  "product": "runweft",
  "phase": "scaffold",
  "execution_enabled": false
} as const);
export type RuntimeStatus = typeof SCAFFOLD_STATUS;
