// Generated by scripts/generate-protocol.mjs; do not edit.
pub const MAX_RAW_MESSAGE_BYTES: usize = 1_048_576;
pub const MAX_CONTAINER_DEPTH: usize = 32;
pub const U64_MAX: &str = "18446744073709551615";
pub const U128_MAX: &str = "340282366920938463463374607431768211455";
pub fn is_known_variant(kind: &str, variant: &str) -> bool {
    matches!(
        (kind, variant),
        ("command", "run.submit")
            | ("command", "run.pause")
            | ("command", "run.resume")
            | ("command", "run.cancel")
            | ("command", "effect.approve")
            | ("command", "effect.reconciliation.propose")
            | ("command", "attempt.result.submit")
            | ("event", "run.admitted")
            | ("event", "run.state.changed")
            | ("event", "graph.revision.state.changed")
            | ("event", "task.state.changed")
            | ("event", "attempt.state.changed")
            | ("event", "effect.intent.recorded")
            | ("event", "effect.state.changed")
            | ("event", "effect.reconciled")
            | ("response", "command.accepted")
            | ("response", "command.rejected")
            | ("error", "protocol.error")
    )
}

pub fn peer_role_allowed(kind: &str, variant: &str, role: &str) -> bool {
    match (kind, variant, role) {
        ("command", "run.submit", role) if ["user"].contains(&role) => true,
        ("command", "run.pause", role) if ["user"].contains(&role) => true,
        ("command", "run.resume", role) if ["user"].contains(&role) => true,
        ("command", "run.cancel", role) if ["user"].contains(&role) => true,
        ("command", "effect.approve", role) if ["user"].contains(&role) => true,
        ("command", "attempt.result.submit", role) if ["worker"].contains(&role) => true,
        ("command", "effect.reconciliation.propose", role) if ["reconciler"].contains(&role) => {
            true
        }
        ("event", "run.admitted", role) if ["coordinator"].contains(&role) => true,
        ("event", "run.state.changed", role) if ["coordinator"].contains(&role) => true,
        ("event", "graph.revision.state.changed", role) if ["coordinator"].contains(&role) => true,
        ("event", "task.state.changed", role) if ["coordinator"].contains(&role) => true,
        ("event", "attempt.state.changed", role) if ["coordinator"].contains(&role) => true,
        ("event", "effect.intent.recorded", role) if ["coordinator"].contains(&role) => true,
        ("event", "effect.state.changed", role) if ["coordinator"].contains(&role) => true,
        ("event", "effect.reconciled", role) if ["coordinator"].contains(&role) => true,
        ("response", "command.accepted", role) if ["coordinator"].contains(&role) => true,
        ("response", "command.rejected", role) if ["coordinator"].contains(&role) => true,
        ("error", "protocol.error", role) if ["coordinator"].contains(&role) => true,
        _ => false,
    }
}

pub fn is_error_code(code: &str) -> bool {
    matches!(
        code,
        "unsupported_version"
            | "unknown_critical_variant"
            | "malformed_payload"
            | "unknown_field"
            | "stale_profile_incarnation"
            | "stale_coordinator_generation"
            | "stale_lease"
            | "invalid_state_transition"
            | "conflict"
            | "not_found"
            | "unauthorized"
            | "resource_exhausted"
            | "requires_confirmation"
            | "unknown_effect"
            | "internal"
    )
}

pub fn retry_advice(code: &str) -> Option<&'static str> {
    match code {
        "unsupported_version" => Some("never"),
        "unknown_critical_variant" => Some("never"),
        "malformed_payload" => Some("never"),
        "unknown_field" => Some("never"),
        "stale_profile_incarnation" => Some("never"),
        "stale_coordinator_generation" => Some("refresh_then_replay_same_command_id"),
        "stale_lease" => Some("never_without_new_lease"),
        "invalid_state_transition" => Some("never_without_new_state"),
        "conflict" => Some("never"),
        "not_found" => Some("never_without_new_reference"),
        "unauthorized" => Some("never_without_new_authority"),
        "resource_exhausted" => Some("same_command_after_limit_window"),
        "requires_confirmation" => Some("never_without_explicit_approval"),
        "unknown_effect" => Some("never_replay_effect_intent"),
        "internal" => Some("never_without_reconciled_command_outcome"),
        _ => None,
    }
}
