// Generated by scripts/generate-protocol.mjs; do not edit.
pub const TRANSITION_COUNT: usize = 72;

pub fn lifecycle_entity_for_event(event: &str) -> Option<&'static str> {
    match event {
        "run.state.changed" => Some("Run"),
        "graph.revision.state.changed" => Some("GraphRevision"),
        "task.state.changed" => Some("Task"),
        "attempt.state.changed" => Some("Attempt"),
        "effect.state.changed" => Some("Effect"),
        "effect.reconciled" => Some("Effect"),
        _ => None,
    }
}

pub fn can_transition(entity: &str, from: &str, to: &str) -> bool {
    matches!(
        (entity, from, to),
        ("Run", "admitted", "running")
            | ("Run", "running", "awaiting_approval")
            | ("Run", "running", "paused")
            | ("Run", "running", "succeeded")
            | ("Run", "running", "failed")
            | ("Run", "running", "cancelled")
            | ("Run", "running", "unknown_effect")
            | ("Run", "awaiting_approval", "running")
            | ("Run", "awaiting_approval", "cancelled")
            | ("Run", "paused", "running")
            | ("Run", "paused", "cancelled")
            | ("Run", "unknown_effect", "running")
            | ("Run", "unknown_effect", "succeeded")
            | ("Run", "unknown_effect", "failed")
            | ("Run", "unknown_effect", "cancelled")
            | ("Run", "admitted", "cancelled")
            | ("GraphRevision", "draft", "validated")
            | ("GraphRevision", "draft", "rejected")
            | ("GraphRevision", "validated", "admitted")
            | ("GraphRevision", "validated", "rejected")
            | ("GraphRevision", "admitted", "superseded")
            | ("Task", "queued", "ready")
            | ("Task", "queued", "skipped")
            | ("Task", "ready", "running")
            | ("Task", "ready", "cancelled")
            | ("Task", "running", "verifying")
            | ("Task", "running", "awaiting_approval")
            | ("Task", "running", "paused")
            | ("Task", "running", "failed")
            | ("Task", "running", "cancelled")
            | ("Task", "running", "unknown_effect")
            | ("Task", "verifying", "succeeded")
            | ("Task", "verifying", "failed")
            | ("Task", "verifying", "unknown_effect")
            | ("Task", "awaiting_approval", "running")
            | ("Task", "awaiting_approval", "cancelled")
            | ("Task", "paused", "ready")
            | ("Task", "paused", "cancelled")
            | ("Task", "failed", "ready")
            | ("Task", "unknown_effect", "succeeded")
            | ("Task", "unknown_effect", "failed")
            | ("Task", "unknown_effect", "ready")
            | ("Task", "queued", "cancelled")
            | ("Attempt", "created", "dispatched")
            | ("Attempt", "created", "cancelled")
            | ("Attempt", "dispatched", "running")
            | ("Attempt", "dispatched", "failed")
            | ("Attempt", "dispatched", "cancelled")
            | ("Attempt", "dispatched", "unknown_effect")
            | ("Attempt", "running", "awaiting_approval")
            | ("Attempt", "running", "paused")
            | ("Attempt", "running", "verifying")
            | ("Attempt", "running", "failed")
            | ("Attempt", "running", "cancelled")
            | ("Attempt", "running", "unknown_effect")
            | ("Attempt", "awaiting_approval", "running")
            | ("Attempt", "awaiting_approval", "cancelled")
            | ("Attempt", "paused", "running")
            | ("Attempt", "paused", "cancelled")
            | ("Attempt", "verifying", "succeeded")
            | ("Attempt", "verifying", "failed")
            | ("Attempt", "verifying", "unknown_effect")
            | ("Attempt", "unknown_effect", "reconciled")
            | ("Effect", "recorded", "authorized")
            | ("Effect", "recorded", "cancelled")
            | ("Effect", "authorized", "invoking")
            | ("Effect", "authorized", "cancelled")
            | ("Effect", "invoking", "applied")
            | ("Effect", "invoking", "failed")
            | ("Effect", "invoking", "unknown_effect")
            | ("Effect", "unknown_effect", "reconciled_applied")
            | ("Effect", "unknown_effect", "reconciled_not_applied")
    )
}

pub fn transition_events(entity: &str, from: &str, to: &str) -> Option<&'static [&'static str]> {
    match (entity, from, to) {
        ("Run", "admitted", "running") => Some(&["run.state.changed"]),
        ("Run", "running", "awaiting_approval") => Some(&["run.state.changed"]),
        ("Run", "running", "paused") => Some(&["run.state.changed"]),
        ("Run", "running", "succeeded") => Some(&["run.state.changed"]),
        ("Run", "running", "failed") => Some(&["run.state.changed"]),
        ("Run", "running", "cancelled") => Some(&["run.state.changed"]),
        ("Run", "running", "unknown_effect") => Some(&["run.state.changed"]),
        ("Run", "awaiting_approval", "running") => Some(&["run.state.changed"]),
        ("Run", "awaiting_approval", "cancelled") => Some(&["run.state.changed"]),
        ("Run", "paused", "running") => Some(&["run.state.changed"]),
        ("Run", "paused", "cancelled") => Some(&["run.state.changed"]),
        ("Run", "unknown_effect", "running") => Some(&["run.state.changed"]),
        ("Run", "unknown_effect", "succeeded") => Some(&["run.state.changed"]),
        ("Run", "unknown_effect", "failed") => Some(&["run.state.changed"]),
        ("Run", "unknown_effect", "cancelled") => Some(&["run.state.changed"]),
        ("Run", "admitted", "cancelled") => Some(&["run.state.changed"]),
        ("GraphRevision", "draft", "validated") => Some(&["graph.revision.state.changed"]),
        ("GraphRevision", "draft", "rejected") => Some(&["graph.revision.state.changed"]),
        ("GraphRevision", "validated", "admitted") => Some(&["graph.revision.state.changed"]),
        ("GraphRevision", "validated", "rejected") => Some(&["graph.revision.state.changed"]),
        ("GraphRevision", "admitted", "superseded") => Some(&["graph.revision.state.changed"]),
        ("Task", "queued", "ready") => Some(&["task.state.changed"]),
        ("Task", "queued", "skipped") => Some(&["task.state.changed"]),
        ("Task", "ready", "running") => Some(&["task.state.changed"]),
        ("Task", "ready", "cancelled") => Some(&["task.state.changed"]),
        ("Task", "running", "verifying") => Some(&["task.state.changed"]),
        ("Task", "running", "awaiting_approval") => Some(&["task.state.changed"]),
        ("Task", "running", "paused") => Some(&["task.state.changed"]),
        ("Task", "running", "failed") => Some(&["task.state.changed"]),
        ("Task", "running", "cancelled") => Some(&["task.state.changed"]),
        ("Task", "running", "unknown_effect") => Some(&["task.state.changed"]),
        ("Task", "verifying", "succeeded") => Some(&["task.state.changed"]),
        ("Task", "verifying", "failed") => Some(&["task.state.changed"]),
        ("Task", "verifying", "unknown_effect") => Some(&["task.state.changed"]),
        ("Task", "awaiting_approval", "running") => Some(&["task.state.changed"]),
        ("Task", "awaiting_approval", "cancelled") => Some(&["task.state.changed"]),
        ("Task", "paused", "ready") => Some(&["task.state.changed"]),
        ("Task", "paused", "cancelled") => Some(&["task.state.changed"]),
        ("Task", "failed", "ready") => Some(&["task.state.changed"]),
        ("Task", "unknown_effect", "succeeded") => Some(&["task.state.changed"]),
        ("Task", "unknown_effect", "failed") => Some(&["task.state.changed"]),
        ("Task", "unknown_effect", "ready") => Some(&["task.state.changed"]),
        ("Task", "queued", "cancelled") => Some(&["task.state.changed"]),
        ("Attempt", "created", "dispatched") => Some(&["attempt.state.changed"]),
        ("Attempt", "created", "cancelled") => Some(&["attempt.state.changed"]),
        ("Attempt", "dispatched", "running") => Some(&["attempt.state.changed"]),
        ("Attempt", "dispatched", "failed") => Some(&["attempt.state.changed"]),
        ("Attempt", "dispatched", "cancelled") => Some(&["attempt.state.changed"]),
        ("Attempt", "dispatched", "unknown_effect") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "awaiting_approval") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "paused") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "verifying") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "failed") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "cancelled") => Some(&["attempt.state.changed"]),
        ("Attempt", "running", "unknown_effect") => Some(&["attempt.state.changed"]),
        ("Attempt", "awaiting_approval", "running") => Some(&["attempt.state.changed"]),
        ("Attempt", "awaiting_approval", "cancelled") => Some(&["attempt.state.changed"]),
        ("Attempt", "paused", "running") => Some(&["attempt.state.changed"]),
        ("Attempt", "paused", "cancelled") => Some(&["attempt.state.changed"]),
        ("Attempt", "verifying", "succeeded") => Some(&["attempt.state.changed"]),
        ("Attempt", "verifying", "failed") => Some(&["attempt.state.changed"]),
        ("Attempt", "verifying", "unknown_effect") => Some(&["attempt.state.changed"]),
        ("Attempt", "unknown_effect", "reconciled") => Some(&["attempt.state.changed"]),
        ("Effect", "recorded", "authorized") => Some(&["effect.state.changed"]),
        ("Effect", "recorded", "cancelled") => Some(&["effect.state.changed"]),
        ("Effect", "authorized", "invoking") => Some(&["effect.state.changed"]),
        ("Effect", "authorized", "cancelled") => Some(&["effect.state.changed"]),
        ("Effect", "invoking", "applied") => Some(&["effect.state.changed"]),
        ("Effect", "invoking", "failed") => Some(&["effect.state.changed"]),
        ("Effect", "invoking", "unknown_effect") => Some(&["effect.state.changed"]),
        ("Effect", "unknown_effect", "reconciled_applied") => Some(&["effect.reconciled"]),
        ("Effect", "unknown_effect", "reconciled_not_applied") => Some(&["effect.reconciled"]),
        _ => None,
    }
}
