// Generated by scripts/generate-protocol.mjs; do not edit.
// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::ProtocolMessage;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: ProtocolMessage = serde_json::from_str(&json).unwrap();
// }

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Runweft version 1.0 command, event, response, and error wire contracts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtocolMessage {
    pub command_id: Option<String>,

    pub coordinator_generation: Option<String>,

    pub extensions: Option<HashMap<String, Option<ProtocolMessag>>>,

    pub kind: ProtocolMessageKind,

    pub payload: Payload,

    pub profile_id: Option<String>,

    pub profile_incarnation: Option<String>,

    pub project_id: Option<String>,

    pub protocol_version: ProtocolVersion,

    pub variant: Variant,

    pub actor: Option<Actor>,

    pub causation_id: Option<String>,

    pub event_id: Option<String>,

    pub graph_revision_id: Option<String>,

    pub observed_at: Option<String>,

    pub policy_revision_id: Option<String>,

    pub run_id: Option<String>,

    pub sequence: Option<String>,

    pub correlation_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Actor {
    pub id: String,

    pub kind: ActorKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActorKind {
    Coordinator,

    Reconciler,

    User,

    Worker,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProtocolMessag {
    Bool(bool),

    PurpleString(String),

    UnionArray(Vec<Option<ProtocolMessag>>),

    UnionMap(HashMap<String, Option<ProtocolMessag>>),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProtocolMessageKind {
    Command,

    Error,

    Event,

    Response,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Payload {
    pub graph_digest: Option<String>,

    pub graph_revision_id: Option<String>,

    pub requested_budget_micro_usd: Option<String>,

    pub run_id: Option<String>,

    pub reason: Option<Reason>,

    pub action_digest: Option<String>,

    pub action_id: Option<String>,

    pub artifact_digest: Option<String>,

    pub effect_intent_id: Option<String>,

    pub grant_revision_id: Option<String>,

    pub policy_revision_id: Option<String>,

    pub target_id: Option<String>,

    pub claimed_outcome: Option<ClaimedOutcome>,

    pub evidence_digest: Option<String>,

    pub evidence_source_id: Option<String>,

    pub attempt_id: Option<String>,

    pub lease: Option<Lease>,

    pub task_id: Option<String>,

    pub from_state: Option<FromState>,

    pub to_state: Option<FromState>,

    pub verification_receipt_id: Option<String>,

    pub accepted_result: Option<AcceptedResult>,

    pub lease_epoch: Option<String>,

    pub verification_receipt: Option<VerificationReceipt>,

    pub effect_class: Option<EffectClass>,

    pub not_applied_evidence: Option<NotAppliedEvidence>,

    pub receipt: Option<Receipt>,

    pub outcome: Option<Outcome>,

    pub command_id: Option<String>,

    pub event_sequence: Option<String>,

    pub error: Option<Error>,

    pub code: Option<Code>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AcceptedResult {
    pub artifact_digest: String,

    pub attempt_id: String,

    pub lease: Lease,

    pub result_id: String,

    pub run_id: String,

    pub task_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lease {
    pub attempt_id: String,

    pub coordinator_generation: String,

    pub epoch: String,

    pub lease_id: String,

    pub profile_id: String,

    pub profile_incarnation: String,

    pub project_id: String,

    pub run_id: String,

    pub task_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClaimedOutcome {
    Applied,

    #[serde(rename = "not_applied")]
    NotApplied,

    Unresolved,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Code {
    Conflict,

    Internal,

    #[serde(rename = "invalid_state_transition")]
    InvalidStateTransition,

    #[serde(rename = "malformed_payload")]
    MalformedPayload,

    #[serde(rename = "not_found")]
    NotFound,

    #[serde(rename = "requires_confirmation")]
    RequiresConfirmation,

    #[serde(rename = "resource_exhausted")]
    ResourceExhausted,

    #[serde(rename = "stale_coordinator_generation")]
    StaleCoordinatorGeneration,

    #[serde(rename = "stale_lease")]
    StaleLease,

    #[serde(rename = "stale_profile_incarnation")]
    StaleProfileIncarnation,

    Unauthorized,

    #[serde(rename = "unknown_critical_variant")]
    UnknownCriticalVariant,

    #[serde(rename = "unknown_effect")]
    UnknownEffect,

    #[serde(rename = "unknown_field")]
    UnknownField,

    #[serde(rename = "unsupported_version")]
    UnsupportedVersion,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EffectClass {
    #[serde(rename = "externally_reconcilable")]
    ExternallyReconcilable,

    #[serde(rename = "opaque_non_idempotent")]
    OpaqueNonIdempotent,

    #[serde(rename = "read_only")]
    ReadOnly,

    #[serde(rename = "remote_idempotent")]
    RemoteIdempotent,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Error {
    pub code: Code,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FromState {
    Admitted,

    Applied,

    Authorized,

    #[serde(rename = "awaiting_approval")]
    AwaitingApproval,

    Cancelled,

    Created,

    Dispatched,

    Draft,

    Failed,

    Invoking,

    Paused,

    Queued,

    Ready,

    Reconciled,

    #[serde(rename = "reconciled_applied")]
    ReconciledApplied,

    #[serde(rename = "reconciled_not_applied")]
    ReconciledNotApplied,

    Recorded,

    Rejected,

    Running,

    Skipped,

    Succeeded,

    Superseded,

    #[serde(rename = "unknown_effect")]
    UnknownEffect,

    Validated,

    Verifying,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotAppliedEvidence {
    pub digest: String,

    pub source_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Outcome {
    Applied,

    #[serde(rename = "not_applied")]
    NotApplied,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Reason {
    #[serde(rename = "operator_action")]
    OperatorAction,

    #[serde(rename = "policy_change")]
    PolicyChange,

    #[serde(rename = "user_request")]
    UserRequest,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Receipt {
    pub action_digest: String,

    pub artifact_digest: String,

    pub effect_intent_id: String,

    pub evidence_digest: String,

    pub evidence_source_id: String,

    pub lease: Lease,

    pub observed_at: String,

    pub receipt_id: String,

    pub target_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationReceipt {
    pub artifact_digest: String,

    pub attempt_id: String,

    pub evidence_digest: String,

    pub observed_at: String,

    pub receipt_id: String,

    pub run_id: String,

    pub task_id: String,

    pub verifier_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProtocolVersion {
    #[serde(rename = "1.0")]
    The10,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Variant {
    #[serde(rename = "attempt.result.submit")]
    AttemptResultSubmit,

    #[serde(rename = "attempt.state.changed")]
    AttemptStateChanged,

    #[serde(rename = "command.accepted")]
    CommandAccepted,

    #[serde(rename = "command.rejected")]
    CommandRejected,

    #[serde(rename = "effect.approve")]
    EffectApprove,

    #[serde(rename = "effect.intent.recorded")]
    EffectIntentRecorded,

    #[serde(rename = "effect.reconciled")]
    EffectReconciled,

    #[serde(rename = "effect.reconciliation.propose")]
    EffectReconciliationPropose,

    #[serde(rename = "effect.state.changed")]
    EffectStateChanged,

    #[serde(rename = "graph.revision.state.changed")]
    GraphRevisionStateChanged,

    #[serde(rename = "protocol.error")]
    ProtocolError,

    #[serde(rename = "run.admitted")]
    RunAdmitted,

    #[serde(rename = "run.cancel")]
    RunCancel,

    #[serde(rename = "run.pause")]
    RunPause,

    #[serde(rename = "run.resume")]
    RunResume,

    #[serde(rename = "run.state.changed")]
    RunStateChanged,

    #[serde(rename = "run.submit")]
    RunSubmit,

    #[serde(rename = "task.state.changed")]
    TaskStateChanged,
}
