// Generate constant-only scaffold status bindings. The protocol schema has a separate generator.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const schema = JSON.parse(await readFile(path.join(root, 'schemas/runtime-status.schema.json'), 'utf8'));
if (schema.type !== 'object' || schema.additionalProperties !== false) throw new Error('Unsupported status schema');
const entries = Object.entries(schema.properties);
if (schema.required.length !== entries.length || entries.some(([name]) => !schema.required.includes(name))) throw new Error('Every field must be required');
const literal = (value) => JSON.stringify(value);
const rustType = (entry) => ({ integer: 'u32', string: "&'static str", boolean: 'bool' })[entry.type];
for (const [name, item] of entries) {
  if (!/^[a-z][a-z0-9_]*$/.test(name) || !rustType(item) || !Object.hasOwn(item, 'const')) throw new Error('Unsupported field');
  if (item.type === 'integer' && (!Number.isInteger(item.const) || item.const < 0 || item.const > 4294967295)) throw new Error('Invalid u32');
  if (item.type === 'string' && (typeof item.const !== 'string' || !/^[a-zA-Z0-9 ._-]+$/.test(item.const))) throw new Error('Unsupported string literal');
  if (item.type === 'boolean' && typeof item.const !== 'boolean') throw new Error('Invalid bool');
}
const rust = `// Generated by scripts/generate-status.mjs; do not edit.
#[derive(Debug, serde::Serialize)]
pub struct RuntimeStatus {
${entries.map(([n, v]) => `    ${n}: ${rustType(v)},`).join('\n')}
}

pub fn scaffold_status() -> RuntimeStatus {
    RuntimeStatus {
${entries.map(([n, v]) => `        ${n}: ${literal(v.const)},`).join('\n')}
    }
}
`;
const ts = `// Generated by scripts/generate-status.mjs; do not edit.
export const SCAFFOLD_STATUS = Object.freeze(${JSON.stringify(Object.fromEntries(entries.map(([n, v]) => [n, v.const])), null, 2)} as const);
export type RuntimeStatus = typeof SCAFFOLD_STATUS;
`;
const check = process.argv.includes('--check');
for (const [relative, contents] of [['crates/runweft-protocol/src/generated_status.rs', rust], ['packages/protocol/src/generated-status.ts', ts]]) {
  const file = path.join(root, relative);
  if (check) {
    if (await readFile(file, 'utf8') !== contents) throw new Error(`Generated contract drift: ${relative}`);
  } else await writeFile(file, contents);
}
console.log(check ? 'Generated scaffold status is current.' : 'Generated scaffold status.');
